### PR TITLE
post-analysis reweighting tools

### PR DESCRIPTION
**Pull request by synapticarbors**
This is a work-in-progress pull request to add my post-analysis reweighting tools to `west_tools` proper. We need to take a careful look at what things might need to be cleaned up, but I wanted to put the code here so we could begin the necessary discussion and code review. 

Several initial things to address:

- The `networkx` version incompatibility that @ajoshpratt previously identified. 
- An undesirable dependency on numba which should be removed and maybe replaced with cython if necessary. 
- If we should be using sparse matrices to handle really large numbers of bins.
- Better documentation of how to use this. 
- In `accumulate_statistics` there is an efficiency issue involving creating a `coo_matrix` for each iteration. This could be resolved by first accumulating indexing and value arrays into a list and building a single sparse matrix at the end, as in this code from a different version of the reweighting tool that I have floating around (it was for an early and custom version of the reweighting that I used in the ion channel work that developed semi-independently and isn't general enough to include in westpa):

```python
def accumulate_statistics(fluxmat_h5file, start_iter, stop_iter, nbins, total_fluxes=None, total_obs=None, rev=False):
    if total_fluxes is None:
        assert total_obs is None
        total_fluxes = np.zeros((nbins, nbins), weight_dtype)
        total_obs = np.zeros((nbins, nbins), np.int64)

    rows = []
    cols = []
    obs = []
    flux = []

    stride = -1 if rev else 1

    for iiter in xrange(start_iter, stop_iter, stride):
        iter_grp = fluxmat_h5file['iterations']['iter_{:08d}'.format(iiter)]

        rows.append(iter_grp['rows'][...])
        cols.append(iter_grp['cols'][...])
        obs.append(iter_grp['obs'][...])
        flux.append(iter_grp['flux'][...])

    rows, cols, obs, flux = map(np.hstack, [rows, cols, obs, flux])

    total_fluxes += sp.coo_matrix((flux, (rows, cols)), shape=(nbins, nbins)).todense()
    total_obs += sp.coo_matrix((obs, (rows, cols)), shape=(nbins, nbins)).todense()

    if start_iter < stop_iter:
        a, b = start_iter, stop_iter
    else:
        b, a = start_iter, stop_iter

    total_pop = np.sum(fluxmat_h5file['bin_populations'][a:b, :], axis=0)

    return total_fluxes, total_obs, total_pop
```

### CODE REVIEW

**Comment by synapticarbors** [comment]
Another item:

- remove ugly and unnecessary `sys.path` hack.

**Comment by mczwier** [comment]
This looks very good. Are you thinking this should be merged as we address these questions, or should we address them and then merge?

I agree about numba; it would be best if we didn't have that dependency long-term, at least until numba stabilizes enough that we can really rely on it to be fast and not likely to break if we don't keep a close eye on the numba mailing list.

My tests a while ago showed that there wasn't a noticeable drop in efficiency (at least on the surface) when using sparse matrices and numerically identical results. I think sparse matrices are the way to go if there aren't compelling reasons not to, as this will prevent users with fine binning from filling up their RAM and crashing the analysis.

Regarding `accumulate_statistics` – just how bad is the efficiency? Is that something we need to address immediately?

**Comment by synapticarbors** [comment]
My preference is to tidy up the loose ends in this PR and then merge it all at once. 

With the `accumulate_statistics` method, the speed-up was pretty substantial if I remember correctly for the particular system I was looking at. I also made a similar modification in a pull request to MSMBuilder (PR #438)  and you can see the results in the following IPython notebook:

http://nbviewer.ipython.org/gist/synapticarbors/6b7fc9ba004bbab42f32

I'll try to work on this a when I can.

**Comment by mczwier** [comment]
Yeah, that's a substantial speedup, and definitely worth doing if we can do so.

**Comment by synapticarbors** [comment]
Official todo list for this PR:

 - [ ] Address networkx version incompatibility
 - [ ] Remove numba dependency
 - [ ] Use sparse matrices throughout to deal with large bin spaces
 - [ ] Modify `accumulate_statistics` to speed up calculation
 - [ ] Remove `sys.path` hack
 - [ ] Either warn that the code is not compatible with recycling simulations or update code to properly handle this mode. I'm leaning toward the former for now.

**Comment by ltchong** [comment]
That's a great idea to include the warning. It would be good to keep an eye out for other situations as well that would warn people from using the tools in a way that would give nonsensical results.

**Comment by synapticarbors** [comment]
After dealing with the issues in testing related to intermediate time points used to generate the assignment file, I think everything looks good here. I added a few key checks in the last commit that deal with users trying to use the tools under inappropriate conditions. 

I'm not entirely thrilled with how we're handling dealing with WE simulation data initially generated with intermediate time points in the trajectory segments. Basically we require the user to down-sample their original west.h5 file. I have a script that does this, but I'm not sure how/if to include/distribute this. It would be preferable to have a flag in `w_assign` to only calculate assignments based on the first and last time points of a trajectory segment. This will require some future modification of this tool since it uses the west.h5 file to gather information about the number of time points and then applies them to the assigments, so this would need to change if there isn't a one-to-one correspondence between the number of saved time points in the west.h5 and assign.h5 files.

@mczwier @ajoshpratt could you both look over the code and make sure everything looks reasonable to you before we merge this? The only thing that I didn't implement is using sparse matrices throughout. This should be done at some point, but can wait for another PR.

**Comment by ajoshpratt** [comment]
Hi all,

Based on some internal conversations regarding the subsampling and how best to handle intermediate timepoints, I've branched the code into the following subrepo:

https://github.com/westpa/west_tools/tree/post-analysis-reweighting-resolution

and made changes to where we no longer need to subsample any of the data.  These changes significantly slowed down the building of the flux matrix, so I did some initial attempts at cythoning the code which sped it back up a good deal; there may be a better way to build the flux matrix using some of numpy's built in methods.  However, I wasn't able to think of any.  Let me know if I'm just being blind?

As this is my first attempt at doing any cython, I would consider this a "first pass" (I haven't profiled or anything), but the speed up is quite significant, and I dare to say it regains almost, if not all, the speed we lost going to full resolution.

In addition, this branch multiplies the flux by the number of time points such that any kinetics calculated by this tool will automatically be reported in units of "per tau", regardless of what time resolution the flux matrix was actually built at, and the user won't have to break from the logic used in tools such as w_kinavg and instead merely divide the output by tau to convert to real time (rather than by subtau).  Let me know if you're uncomfortable with reporting flux*npts, instead of simply raw flux, or with any other change.

**Comment by ajoshpratt** [comment]
I think, at this time, we're good to merge.  Unless anyone has any disagreements.

**Pull request merged**
