### PR TITLE
Event Duration Kinetics Pull Request

### PR DESCRIPTION
**Pull request by ajoshpratt**
Hello all,

I believe this code is ready to be merged.  After comparing results internally against the 2011 JCTC paper, the results it obtains are the same for a 2 state, 3 bin system.

The code works as follows: w_assign creates a new dataset, called statelabels, which is an instantaneous, memoryless state assignment (it is exactly like the bin assignment dataset, except that instead of containing bin assignment information, it contains the state label each bin has; for a two state system, this is 0, 1, or 2, for unknown).  The code that w_kinetics relies on, _kinetics.pyx, uses a new counter, and pulls this information instead of the trajlabel information, as before, to determine the length of the event duration.  Other than that, the data it returns is the same.

Minor adjustments were made to the histogram logic in w_eddist itself to fix bugs in the event of no event duration information.

No new features are introduced in this branch.

### CODE REVIEW

**Comment by mczwier** [comment]
Looks good to me. @ajoshpratt, want to do the honors?

**Comment by ajoshpratt** [comment]
Wheeee!

**Comment by synapticarbors** [comment]
Were tests run and appropriate tests updated/added?

**Comment by ajoshpratt** [comment]
... and that's a no.  There are no unit tests for _kinetics.pyx's find_macrostate_transitions, which is the function which was modified most heavily.  Some of the assignment functions (such as are used for w_assign) were modified, but only insofar as was necessary to create an extra dataset, and there seem to be no unit tests for those, either.  I can create a revert merge request since I seem to be quick on the trigger today, if we feel we should.

**Comment by synapticarbors** [comment]
No reason to revert this pull request. If there weren't any tests for things that were modified here, that's fine. I just wanted to make sure that if they were that they still passed and/or were updated to reflect the changes so that we didn't have new failing tests. At some point it would be good to add appropriate unit tests to increase our code coverage. 

In general going forward, new features should have tests added as well also increase coverage for old stuff. I'm guilty of not following this advice, but I think it's a good policy to put in place.

**Pull request merged**
