### PR TITLE
Yaml branch

### PR DESCRIPTION
**Pull request by ASinanSaglam**
Added a system class to yamlcfg.py to allow for system creation directly from the YAML config file (attempting to call WESTSytem results in a circular dependency). 

Added an option to the YAML config file to allow for modification/creation of the system and system options.

### CODE REVIEW

**Comment by mczwier** [comment]
Looks good.

What are the chances of getting a few unit tests for this? I'd specifically be interested in tests that ascertain proper resolution of conflicts (or assertion of lack of conflicts) between system.py and YAML, a test that asserts that everything runs fine in the absence of YAML system information, and a test that asserts that the bins you want are the bins you get.

**Comment by ASinanSaglam** [comment]
Will add! 

I tested it for: 
 - No driver, only YAML options
 - No YAML options, only driver
 - That all options are overwritten by the YAML config

Will do:
  - Make sure the bin boundaries are actually the ones we want (I only checked the counts)
  - Add more logging to each step to make it more verbose as to which paths are being used for system generation.

One thing to note: I was attempting to allow for a half complete set of options in the driver and then you could complete the rest from the YAML file but that doesn't seem smart, I think that's too prone for errors. I fixed that and now you have to have a full set of options for both if you want to overwrite using the YAML route.

**Comment by mczwier** [comment]
Sounds very good.

**Comment by ASinanSaglam** [comment]
Checked bin boundaries, they are correct, I tried with with and without the YAML options.

Added more verbose statements, it now prints if the system is building off of the YAML file, updating or using only the system driver. It also logs what variables it's overwriting so you can make sure things are working from the --debug output. 

One thing I attempted but want to avoid for now is the logging of overwritten values (previous ones and the current ones) since if you have a large bin space for example that could get nasty really quickly. I'm going to later attempt logging the actual values that are changed and into what but I want to play around with some printing options first (also with the logging facilities).

**Comment by ASinanSaglam** [comment]
Also made a gist for a sample west.cfg for convenience. The YAML options are commented out, you can play around with them as you like, please let me know if you discover a bug! 

https://gist.github.com/bcf439563a48c8427e13.git

**Comment by mczwier** [comment]
Looks good. Is there any chance you can formalize the tests you ran by adding unit tests to the distribution? (See https://github.com/westpa/wwmgr/tree/master/test_work_managers for examples.) I imagine these could go in a new directory lib/tests. The purpose is to ensure that the changes you've made aren't broken by other people's future work.

**Comment by ASinanSaglam** [comment]
Sure, will do as soon as I have some down time!

**Comment by mczwier** [comment]
Should we merge this branch and add the unit tests as an issue, or would you like to wait on a merge until the tests are in place?

**Comment by ASinanSaglam** [comment]
I would feel more comfortable with it after placing in tests, it won't take long, I'll get it done within the week so no worries! :smile:

**Comment by ASinanSaglam** [comment]
I added a test class to west_tools/tests/ folder since there were already some tests there I thought that might be the appropriate place. 

I tested the tests (I know, I know) by importing them in a script as well. I wasn't sure the setUp and tearDown functions were required or not (since I wasn't sure if this was  the unit test module or not, it looked like it but I didn't see any imports) but of course I can add them if need be. 

The tests check to ensure the driver is loaded, the options are overwritten properly (and not kept same if they weren't supposed to be) also it checks if the system can be built solely on the YAML config file (in two separate tests). 

Please let me know if I should add more/make further changes!

**Comment by mczwier** [comment]
Looks good, Ali. Thanks for taking the time to do this well!
I'll merge if there are no further points to discuss.

**Comment by ASinanSaglam** [comment]
Fantastic, I think it's good on my end for now as far as I can tell, the only thing is to test this and ensure it behaves as expected and fix any remaining bugs of course which I'm sure we'll find as we play around with it.

**Pull request merged**
